version: '3'

services:

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports: 
      - "8080:80"
    

  app:
    build:
      context: node
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/user/src/app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db

  db:
    build:
      context: mysql
    container_name: db
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./mysql/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysql_data: